### ISSUE TITLE
multiple locations found

### ISSUE THREAD

**Issue by olasabet** [QSCD/BaSiC#3]
I installed the BaSiC plugin as outlined and have used it before on Fiji. Recently I tried to use it again and it hit the following incompatibility. I don't know where to start from in troubleshooting. 
---------------------------------------------------
[Sun Oct 03 17:30:57 CEST 2021] [ERROR] [] null
java.lang.NoSuchMethodException: Could not find method edu.emory.mathcs.utils.ConcurrencyUtils.getThreadsBeginN_1D()I
There was a problem with the class edu.emory.mathcs.utils.ConcurrencyUtils which can be found here:
/Users/work/Applications/Fiji.app/jars/jtransforms-2.4.jar
/Users/work/Applications/Fiji.app/jars/parallelcolt-0.9.4.jar

WARNING: multiple locations found!
java.lang.NoSuchMethodError: edu.emory.mathcs.utils.ConcurrencyUtils.getThreadsBeginN_1D()I
	at cern.colt.matrix.tdouble.impl.DenseDoubleMatrix1D.zSum(Unknown Source)
	at BaSiC_.matrixMean(BaSiC_.java:1041)
	at BaSiC_.ShadingCorrection(BaSiC_.java:540)
	at BaSiC_.exec(BaSiC_.java:403)
	at BaSiC_.processDialog(BaSiC_.java:259)
	at BaSiC_.showDialog(BaSiC_.java:164)
	at BaSiC_.run(BaSiC_.java:113)
	at ij.IJ.runUserPlugIn(IJ.java:241)
	at ij.IJ.runPlugIn(IJ.java:204)
	at ij.Executer.runCommand(Executer.java:150)
	at ij.Executer.run(Executer.java:68)
	at java.lang.Thread.run(Thread.java:748)

	at cern.colt.matrix.tdouble.impl.DenseDoubleMatrix1D.zSum(Unknown Source)
	at BaSiC_.matrixMean(BaSiC_.java:1041)
	at BaSiC_.ShadingCorrection(BaSiC_.java:540)
	at BaSiC_.exec(BaSiC_.java:403)
	at BaSiC_.processDialog(BaSiC_.java:259)
	at BaSiC_.showDialog(BaSiC_.java:164)
	at BaSiC_.run(BaSiC_.java:113)
	at ij.IJ.runUserPlugIn(IJ.java:241)
	at ij.IJ.runPlugIn(IJ.java:204)
	at ij.Executer.runCommand(Executer.java:150)
	at ij.Executer.run(Executer.java:68)
	at java.lang.Thread.run(Thread.java:748)

**Comment by olasabet** [comment]
Fixed thanks!

**Comment by AntonioMargheriti** [comment]
Hello olasabet

I currently have the same error message as you did.  I've already tried the troubleshooting approach described on the BaSiC website - I did not have a jtransforms2.4.jar file so I don't think that any issue can stem from there. Could you tell me how you fixed this issue?

Cheers

**Comment by olasabet** [comment]
Hi Antonio, 
yes go to your jars folder (for example for me /Users/work/Applications/Fiji.app/jars/) then look for the files that start with jtransforms and parallelcolt. You will find two of them (hence the error), delete the duplicate or take it out of the jars folder somewhere else until you are sure things are running. Cheers

**Comment by AntonioMargheriti** [comment]
Hi olasabet

I see, thanks a lot - it's working now.

Cheers

**Comment by klai001** [comment]
Hi I have the same error but I dont have duplicate files in my jar. There's only one  jtransforms and parallelcolt in my jars folder. Anyhow i shifted them to plugins folder and i get the same error notif ( below appended) _`
[ERROR] java.lang.NoSuchMethodException: Could not find method edu.emory.mathcs.utils.ConcurrencyUtils.getThreadsBeginN_1D()I
There was a problem with the class edu.emory.mathcs.utils.ConcurrencyUtils which can be found here:
/C:/Users/KEIONN~1/Desktop/Fiji.app/plugins/jtransforms-2.4.jar
/C:/Users/KEIONN~1/Desktop/Fiji.app/plugins/parallelcolt-0.9.4.jar

WARNING: multiple locations found!
java.lang.NoSuchMethodError: edu.emory.mathcs.utils.ConcurrencyUtils.getThreadsBeginN_1D()I
	at cern.colt.matrix.tdouble.DoubleMatrix1D.assign(Unknown Source)
	at cern.colt.matrix.tdouble.impl.DenseDoubleMatrix1D.assign(Unknown Source)
	at BaSiC_.ShadingCorrection(BaSiC_.java:563)
	at BaSiC_.exec(BaSiC_.java:403)
	at BaSiC_.processDialog(BaSiC_.java:259)
	at BaSiC_.showDialog(BaSiC_.java:164)
	at BaSiC_.run(BaSiC_.java:113)
	at ij.IJ.runUserPlugIn(IJ.java:243)
	at ij.IJ.runPlugIn(IJ.java:204)
	at ij.Executer.runCommand(Executer.java:152)
	at ij.Executer.run(Executer.java:70)
	at java.lang.Thread.run(Thread.java:748)

	at cern.colt.matrix.tdouble.DoubleMatrix1D.assign(Unknown Source)
	at cern.colt.matrix.tdouble.impl.DenseDoubleMatrix1D.assign(Unknown Source)
	at BaSiC_.ShadingCorrection(BaSiC_.java:563)
	at BaSiC_.exec(BaSiC_.java:403)
	at BaSiC_.processDialog(BaSiC_.java:259)
	at BaSiC_.showDialog(BaSiC_.java:164)
	at BaSiC_.run(BaSiC_.java:113)
	at ij.IJ.runUserPlugIn(IJ.java:243)
	at ij.IJ.runPlugIn(IJ.java:204)
	at ij.Executer.runCommand(Executer.java:152)
	at ij.Executer.run(Executer.java:70)
	at java.lang.Thread.run(Thread.java:748)
`_
